// Architected by Khalid Hasan Limon.

package com.example.ui.inventory

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color as AndroidColor
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.os.Environment
import android.widget.Toast
import com.example.data.InventoryItem
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class ExportService {

    suspend fun exportToPdf(context: Context, items: List<InventoryItem>, isDigitalMode: Boolean) {
        withContext(Dispatchers.IO) {
            try {
                val pdfDocument = PdfDocument()
                val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 Size
                val page = pdfDocument.startPage(pageInfo)
                val canvas = page.canvas
                val paint = Paint()

                // Background
                if (isDigitalMode) {
                    paint.color = AndroidColor.rgb(240, 248, 255) // AliceBlue for digital
                    canvas.drawRect(0f, 0f, pageInfo.pageWidth.toFloat(), pageInfo.pageHeight.toFloat(), paint)
                } else {
                    paint.color = AndroidColor.WHITE
                    canvas.drawRect(0f, 0f, pageInfo.pageWidth.toFloat(), pageInfo.pageHeight.toFloat(), paint)
                }

                // Title
                paint.color = AndroidColor.BLACK
                paint.textSize = 24f
                paint.isFakeBoldText = true
                val sdf = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault())
                val dateStr = sdf.format(Date())
                canvas.drawText("Polwel ERP System - Inventory Report", 50f, 50f, paint)
                paint.textSize = 14f
                paint.isFakeBoldText = false
                canvas.drawText("Generated on: $dateStr", 50f, 80f, paint)

                var yOffset = 120f
                paint.textSize = 16f
                paint.isFakeBoldText = true
                
                // Table Headers
                if (isDigitalMode) {
                    paint.color = AndroidColor.DKGRAY
                }
                canvas.drawText("Item Name", 50f, yOffset, paint)
                canvas.drawText("Category", 200f, yOffset, paint)
                canvas.drawText("Stock", 350f, yOffset, paint)
                canvas.drawText("Cost/Unit", 450f, yOffset, paint)

                yOffset += 30f
                paint.isFakeBoldText = false
                paint.textSize = 14f
                paint.color = AndroidColor.BLACK

                // Rows
                items.forEach { item ->
                    canvas.drawText(item.itemName, 50f, yOffset, paint)
                    canvas.drawText(item.category, 200f, yOffset, paint)
                    canvas.drawText("${item.currentStock} ${item.unitMeasure}", 350f, yOffset, paint)
                    canvas.drawText("BDT ${item.unitCost}", 450f, yOffset, paint)
                    yOffset += 30f
                }

                // Footer
                paint.color = AndroidColor.GRAY
                paint.textSize = 12f
                paint.textAlign = Paint.Align.CENTER
                canvas.drawText("Generated by Polwel ERP System | Architected by Khalid Hasan Limon", pageInfo.pageWidth / 2f, pageInfo.pageHeight - 30f, paint)

                pdfDocument.finishPage(page)

                val dir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
                val file = File(dir, "Polwel_ERP_Report_${System.currentTimeMillis()}.pdf")
                pdfDocument.writeTo(FileOutputStream(file))
                pdfDocument.close()

                withContext(Dispatchers.Main) {
                    Toast.makeText(context, "Report saved to Downloads: ${file.name}", Toast.LENGTH_LONG).show()
                }

            } catch (e: Exception) {
                e.printStackTrace()
                withContext(Dispatchers.Main) {
                    Toast.makeText(context, "Export Failed: ${e.message}", Toast.LENGTH_LONG).show()
                }
            }
        }
    }
}
